
DB_USER="benjamin"
TABLENAME="keyframe"

# Database names.
ESM_DATABASE="ESM_KEYFRAMES"
FIND_ONLY_DATABASE="FIND_ONLY_KEYFRAMES"
FIND_MATCH_DATABASE="FIND_MATCH_KEYFRAMES"


psql --username $DB_USER $ESM_DATABASE -c "DELETE FROM $TABLENAME"
psql --username $DB_USER $FIND_ONLY_DATABASE -c "DELETE FROM $TABLENAME"
psql --username $DB_USER $FIND_MATCH_DATABASE -c "DELETE FROM $TABLENAME"
